# Generated by Django 3.1 on 2024-11-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBD', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='talla',
            field=models.IntegerField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')]),
        ),
    ]
