# Generated by Django 3.1 on 2024-11-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBD', '0002_auto_20241107_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='talla',
            field=models.IntegerField(choices=[('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL')]),
        ),
    ]
