# Generated by Django 3.1 on 2024-11-07 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBD', '0004_auto_20241107_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='talla',
            field=models.IntegerField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')]),
        ),
    ]
